# api-gateway application configuration
server:
  port: 8090

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      server:
        webflux:
          routes:
            # Grafana - serves from /grafana subpath (GF_SERVER_SERVE_FROM_SUB_PATH=true)
            - id: grafana
              uri: ${GRAFANA_URL:http://localhost:3000}
              predicates:
                - Path=/grafana,/grafana/**
              filters:
                - StripPrefix=0
                - PreserveHostHeader
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

            # Prometheus - supports subpath via --web.external-url=/prometheus
            - id: prometheus
              uri: ${PROMETHEUS_URL:http://localhost:9090}
              predicates:
                - Path=/prometheus,/prometheus/**
              filters:
                - StripPrefix=0

            # Loki - redirect to Grafana Explore with Loki datasource
            - id: loki-root
              uri: ${GRAFANA_URL:http://localhost:3000}
              predicates:
                - Path=/loki
              filters:
                - RedirectTo=302, /grafana/explore?orgId=1&datasource=loki

            # Loki API - needs path stripping for API calls
            - id: loki-api
              uri: ${LOKI_URL:http://localhost:3100}
              predicates:
                - Path=/loki/**
              filters:
                - StripPrefix=1

            # IBM MQ Web Console - serves at /ibmmq/console/ path
            - id: ibmmq
              uri: ${IBMMQ_URL:https://localhost:9443}
              predicates:
                - Path=/ibmmq,/ibmmq/**
              filters:
                - StripPrefix=0

            # Kafdrop - serves from /kafdrop subpath (SERVER_SERVLET_CONTEXTPATH=/kafdrop)
            - id: kafdrop
              uri: ${KAFDROP_URL:http://localhost:9000}
              predicates:
                - Path=/kafdrop,/kafdrop/**
              filters:
                - StripPrefix=0

            # Perf-Tester API
            - id: perf-tester
              uri: ${PERF_TESTER_URL:http://localhost:8080}
              predicates:
                - Path=/api/**
              filters:
                - StripPrefix=0

            # Tempo - redirect to Grafana Explore with Tempo datasource
            - id: tempo-root
              uri: ${GRAFANA_URL:http://localhost:3000}
              predicates:
                - Path=/tempo
              filters:
                - RedirectTo=302, /grafana/explore?orgId=1&datasource=tempo

            # Tempo API - needs path stripping for API calls
            - id: tempo-api
              uri: ${TEMPO_URL:http://localhost:3200}
              predicates:
                - Path=/tempo/**
              filters:
                - StripPrefix=1

            # Sonar - has web context configured
            - id: sonar
              uri: ${SONAR_URL:http://localhost:9000}
              predicates:
                - Path=/sonar,/sonar/**
              filters:
                - StripPrefix=0

            # Config Server
            - id: config-server
              uri: ${CONFIG_SERVER_URL:http://localhost:8888}
              predicates:
                - Path=/config,/config/**
              filters:
                - StripPrefix=1
          httpclient:
            ssl:
              use-insecure-trust-manager: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: api-gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
