# ibm-mq-consumer application configuration
server:
  port: 8081
  address: 0.0.0.0

spring:
  jms:
    pool:
      enabled: true
      max-connections: 20
      max-sessions-per-connection: 10
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.example.ibmmqconsumer.serialization.AvroSerializer
      acks: 1
      compression-type: lz4
      properties:
        linger.ms: 5
        batch.size: 65536
    consumer:
      group-id: ibm-mq-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.example.ibmmqconsumer.serialization.AvroDeserializer
  task:
    execution:
      thread-name-prefix: mq-consumer-

ibm:
  mq:
    queue-manager: QM1
    channel: DEV.ADMIN.SVRCONN
    conn-name: localhost(1414)
    user: admin
    password: passw0rd

app:
  mq:
    queue:
      inbound: DEV.QUEUE.2
      outbound: DEV.QUEUE.1
  kafka:
    topic:
      request: mq-requests
      response: mq-responses
    consumer:
      concurrency: 20

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        jms: true
        mq.e2e.latency: true
      percentiles:
        http.server.requests: 0.95,0.99
        jms: 0.95,0.99

logging:
  level:
    com.example.ibmmqconsumer: INFO
