# perf-tester Docker profile configuration
spring:
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/XEPDB1

ibm:
  mq:
    conn-name: ibm-mq(1414)

app:
  grafana:
    url: http://grafana:3000
  prometheus:
    url: http://prometheus:9090
  healthcheck:
    kafka:
      bootstrap-servers: kafka:9092
    oracle:
      url: jdbc:oracle:thin:@oracle:1521/XEPDB1
