# perf-tester Docker profile configuration
spring:
  datasource:
    url: jdbc:oracle:thin:@oracle:1521/XEPDB1
  data:
    redis:
      host: redis

ibm:
  mq:
    conn-name: ibm-mq(1414)

app:
  grafana:
    url: http://grafana:3000
  prometheus:
    url: http://prometheus:9090
  healthcheck:
    kafka:
      host: kafka
      port: 9092
    mq:
      host: ibm-mq
      port: 1414
    oracle:
      host: oracle
      port: 1521
    redis:
      host: redis
      port: 6379
