# perf-tester Kubernetes profile configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@perf-oracle:1521/XEPDB1}
    username: ${SPRING_DATASOURCE_USERNAME:perfuser}
    password: ${SPRING_DATASOURCE_PASSWORD:perfpass}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:perf-redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

ibm:
  mq:
    conn-name: ${IBM_MQ_CONNNAME:perf-ibm-mq(1414)}

app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:perf-kafka:9092}
  grafana:
    url: ${GRAFANA_URL:http://perf-grafana:3000}
  prometheus:
    url: ${PROMETHEUS_URL:http://perf-prometheus:9090}
  healthcheck:
    kafka:
      host: perf-kafka
      port: 9092
    mq:
      host: perf-ibm-mq
      port: 1414
    oracle:
      host: perf-oracle
      port: 1521
    redis:
      host: perf-redis
      port: 6379
