apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perf-api-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: perf-demo
  source:
    repoURL: https://github.com/<org>/spring-boot-4-perf-demo.git
    targetRevision: HEAD
    path: infrastructure/helm/api-gateway
    helm:
      valuesObject:
        image:
          repository: api-gateway
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: perf-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
