apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perf-trivy-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: perf-demo
  source:
    repoURL: https://aquasecurity.github.io/helm-charts
    chart: trivy-operator
    targetRevision: 0.27.0
    helm:
      valuesObject:
        operator:
          scanJobsConcurrentLimit: 3
          scanJobsRetryDelay: 30s
        trivy:
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          ignoreUnfixed: true
        serviceMonitor:
          enabled: true
        targetNamespaces: "perf-demo"
  destination:
    server: https://kubernetes.default.svc
    namespace: perf-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
