apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perf-trivy-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: perf-demo
  source:
    repoURL: https://aquasecurity.github.io/helm-charts
    chart: trivy-operator
    targetRevision: 0.27.0
    helm:
      valuesObject:
        operator:
          scanJobsConcurrentLimit: 3
          scanJobsRetryDelay: 30s
        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "/metrics"
          prometheus.io/job: "trivy-operator"
        trivyOperator:
          scanJobPodTemplateContainerSecurityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
          scanJobCustomVolumes:
            - name: docker-sock
              hostPath:
                path: /var/run/docker.sock
          scanJobCustomVolumesMount:
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
        trivy:
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          ignoreUnfixed: true
          resources:
            requests:
              cpu: 100m
              memory: 256M
            limits:
              cpu: "1"
              memory: 1Gi
        serviceMonitor:
          enabled: false
        targetNamespaces: "perf-demo"
  destination:
    server: https://kubernetes.default.svc
    namespace: perf-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
