# ibm-mq-consumer Docker profile configuration
spring:
  kafka:
    bootstrap-servers: kafka:9092
    properties:
      schema.registry.url: http://schema-registry:8081

ibm:
  mq:
    conn-name: ibm-mq(1414)
