# perf-tester application configuration
server:
  port: 8080
  address: 0.0.0.0

spring:
  data:
    redis:
      host: localhost
      port: 6379
  jms:
    pool:
      enabled: true
      max-connections: 20
      max-sessions-per-connection: 10
  task:
    execution:
      thread-name-prefix: mq-sender-

ibm:
  mq:
    queue-manager: QM1
    channel: DEV.ADMIN.SVRCONN
    conn-name: localhost(1414)
    user: admin
    password: passw0rd

app:
  kubernetes:
    export-enabled: false
  kafka:
    bootstrap-servers: localhost:9092
  mq:
    queue:
      inbound: DEV.QUEUE.1
      outbound: DEV.QUEUE.2
  grafana:
    url: http://localhost:3000
    export-path: ./grafana-exports
    api-key:
  prometheus:
    url: http://localhost:9090
    export-path: ./prometheus-exports
  export:
    path: ./test-exports
  perf:
    metrics-propagation-delay-ms: 16000
    tps-window-ms: 60000
    grafana-buffer-before-ms: 60000
    grafana-buffer-after-ms: 30000
    prometheus-buffer-seconds: 60
    prometheus-step-seconds: 15
  healthcheck:
    enabled: true
    interval-ms: 60000
    connection-timeout-ms: 5000
    kafka:
      host: localhost
      port: 9092
    mq:
      host: localhost
      port: 1414
    oracle:
      host: localhost
      port: 1521
    redis:
      host: localhost
      port: 6379

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        jms: true
        mq.e2e.latency: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
        jms: 0.5,0.95,0.99
        mq.e2e.latency: 0.5,0.75,0.9,0.95,0.99

logging:
  level:
    org.springframework.jms: INFO
    com.ibm.mq: INFO
    com.ibm.msg: INFO
