# perf-tester application configuration
server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:h2:file:./data/perfdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  jms:
    pool:
      enabled: true
      max-connections: 20
      max-sessions-per-connection: 10
  task:
    execution:
      thread-name-prefix: mq-sender-

ibm:
  mq:
    queue-manager: QM1
    channel: DEV.ADMIN.SVRCONN
    conn-name: ${IBM_MQ_CONNNAME:localhost(1414)}
    user: admin
    password: passw0rd

app:
  kubernetes:
    namespace: perf-demo
    export-enabled: false
  kafka:
    bootstrap-servers: localhost:9092
  mq:
    queue:
      inbound: DEV.QUEUE.1
      outbound: DEV.QUEUE.2
  monitoring:
    inbound-queue: DEV.QUEUE.1
    outbound-queue: DEV.QUEUE.2
    kafka-request-consumer-group: kafka-consumer-group
    kafka-response-consumer-group: ibm-mq-consumer-group
  dashboards:
    - label: Grafana
      url: /grafana
      enabled: true
    - label: Prometheus
      url: /prometheus
      enabled: true
    - label: Kafdrop
      url: /kafdrop
      enabled: true
    - label: Redis Commander
      url: /redis-commander
      enabled: true
    - label: Loki
      url: /grafana/explore?orgId=1&left=%7B%22datasource%22:%22loki%22%7D
      enabled: true
    - label: IBM MQ
      url: /ibmmq
      enabled: true
    - label: SonarQube
      url: /sonar
      enabled: false
  grafana:
    url: http://localhost:3000
    export-path: ./grafana-exports
    api-key:
  prometheus:
    url: http://localhost:9090
    export-path: ./prometheus-exports
  export:
    path: ./test-exports
  loki:
    url: http://localhost:3100
  perf:
    metrics-propagation-delay-ms: 16000
    tps-window-ms: 60000
    grafana-buffer-before-ms: 60000
    grafana-buffer-after-ms: 30000
    prometheus-buffer-seconds: 60
    prometheus-step-seconds: 15
  healthcheck:
    enabled: true
    interval-ms: 60000
    connection-timeout-ms: 5000
    kafka:
      host: localhost
      port: 9092
    mq:
      host: localhost
      port: 1414
    redis:
      host: localhost
      port: 6379

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        jms: true
        mq.e2e.latency: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
        jms: 0.5,0.95,0.99
        mq.e2e.latency: 0.5,0.75,0.9,0.95,0.99

logging:
  level:
    org.flywaydb: INFO
    org.springframework.jms: INFO
    com.ibm.mq: INFO
    com.ibm.msg: INFO