# perf-tester Kubernetes profile configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://perf-postgres:5432/perfdb}
    username: ${SPRING_DATASOURCE_USERNAME:perfuser}
    password: ${SPRING_DATASOURCE_PASSWORD:perfpass}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:perf-redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

ibm:
  mq:
    conn-name: ${IBM_MQ_CONNNAME:perf-ibm-mq(1414)}

app:
  kubernetes:
    export-enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:perf-kafka:9092}
  loki:
    url: ${LOKI_URL:http://perf-loki:3100}
  grafana:
    url: ${GRAFANA_URL:http://perf-grafana:3000}
  prometheus:
    url: ${PROMETHEUS_URL:http://perf-prometheus:9090}
  healthcheck:
    kafka:
      host: perf-kafka
      port: 9092
    mq:
      host: perf-ibm-mq
      port: 1414
    postgres:
      host: perf-postgres
      port: 5432
    redis:
      host: perf-redis
      port: 6379
