apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perf-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: perf-demo
  source:
    repoURL: https://github.com/<org>/spring-boot-4-perf-demo.git
    targetRevision: HEAD
    path: infrastructure/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
